### ISSUE TITLE
pip install ttsmms issue

### ISSUE THREAD

**Issue by ARTHARKING55** [wannaphong/ttsmms#18]
× Building wheel for monotonic-align (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      [C:\Users\admin\AppData\Local\Temp\pip-build-env-nrrf1rmc\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py:108](file:///C:/Users/admin/AppData/Local/Temp/pip-build-env-nrrf1rmc/overlay/Lib/site-packages/setuptools/config/pyprojecttoml.py:108): _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\monotonic_align
      copying src\monotonic_align\__init__.py -> build\lib.win-amd64-cpython-312\monotonic_align
      running build_ext
      cythoning src/core.pyx to src\core.c
      building 'monotonic_align.core' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

**Comment by wannaphong** [comment]
https://stackoverflow.com/a/64262038
