### ISSUE TITLE
Tried to install it on Windows 11 and got this error:

### ISSUE THREAD

**Issue by JohnClaw** [wannaphong/ttsmms#6]
Error's text: "Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/" I downloaded "Microsoft C++ Build Tools", installed it and rebooted my PC but got the same error again. How can i fix it?

**Comment by JohnClaw** [comment]
I managed to solve this issue by myself. Googled a lot and finally found the solution. Suppose that all installed properly.

**Comment by RwGrid** [comment]
how to solve it
